# Generated by Django 4.1.7 on 2023-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Accounting", "Accounting"),
                            ("admini", "Administrative Assistant"),
                            ("architect", "Architect"),
                            ("cp", "Computer Programmer"),
                            ("con", "Construction"),
                            ("cs", "Ustomer Service"),
                            ("dbadmini", "Database Administrator"),
                            ("hr", "Human Resources"),
                            ("marketing", "Marketing"),
                            ("retail", "Retail"),
                            ("sales", "Sales"),
                        ],
                        max_length=64,
                    ),
                ),
                ("post_name", models.CharField(max_length=64)),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("phd", "PhD"),
                            ("PG", "Post Graduate"),
                            ("UG", "Under Graduate"),
                            ("Dip", "Diploma"),
                            ("X", "SSLC"),
                        ],
                        max_length=64,
                    ),
                ),
                ("skills", models.TextField(max_length=60)),
                ("experience", models.IntegerField()),
                ("no_of_vacancy", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("salary", models.IntegerField()),
                (
                    "employment_type",
                    models.CharField(
                        choices=[("full", "Full Time"), ("part", "Part Time")],
                        max_length=64,
                    ),
                ),
                ("last_date", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
