# Generated by Django 4.2.3 on 2023-08-09 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_appliedmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpostmodel",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobposts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobpostmodel",
            name="experience",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="jobpostmodel",
            name="salary",
            field=models.FloatField(),
        ),
    ]
