# Generated by Django 4.1.7 on 2023-05-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_jobpostmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat_name", models.CharField(max_length=64)),
                ("no_of_vacancy", models.IntegerField()),
                (
                    "image",
                    models.ImageField(
                        default="default/logo.png", upload_to="core/category/image/"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="login",
        ),
        migrations.DeleteModel(
            name="Register",
        ),
    ]
