# Generated by Django 4.1.7 on 2023-04-29 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("address", models.CharField(max_length=150)),
                ("contact_no", models.IntegerField()),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("T", "Transgender")],
                        max_length=2,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("phd", "PhD"),
                            ("PG", "Post Graduate"),
                            ("UG", "Under Graduate"),
                            ("Dip", "Diploma"),
                            ("X", "SSLCC"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("Bba", "BBA"),
                            ("Bcom", "Bcom"),
                            ("Bca", "BCA"),
                            ("Mcom", "Mcom"),
                            ("Mba", "MBA"),
                            ("Mca", "MCA"),
                            ("civil", "Civil Engineering"),
                            ("Nurse", "Bsc Nursing"),
                        ],
                        max_length=64,
                    ),
                ),
                ("institution", models.CharField(max_length=64)),
                ("year_of_passing", models.ImageField(upload_to="")),
                ("percetage", models.IntegerField()),
                ("experience", models.IntegerField()),
                ("skills", models.CharField(max_length=150)),
                ("resume", models.FileField(upload_to="")),
                (
                    "image",
                    models.ImageField(
                        default="default/user.png", upload_to="accounts/profile/image/"
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
