# Generated by Django 4.1.7 on 2023-04-29 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilemodel",
            name="contact_no",
        ),
    ]
