# Generated by Django 4.1.7 on 2023-06-30 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualificationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("course_name", models.CharField(max_length=64)),
                ("description", models.TextField(max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="profilemodel",
            name="course",
        ),
        migrations.RemoveField(
            model_name="profilemodel",
            name="percetage",
        ),
        migrations.RemoveField(
            model_name="profilemodel",
            name="user",
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="experience",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.CreateModel(
            name="JobSeekerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.profilemodel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="qualification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.qualificationmodel",
            ),
        ),
    ]
