# Generated by Django 4.1.7 on 2023-05-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_profilemodel_contact_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="contact_no",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
