# Generated by Django 4.1.7 on 2023-05-02 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0004_employermodel_jobseekermodel_delete_profilemodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobSeekerModel",
            new_name="ProfileModel",
        ),
    ]
