# Generated by Django 4.1.7 on 2023-05-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_rename_jobseekermodel_profilemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employermodel",
            name="address",
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="year_of_passing",
            field=models.IntegerField(),
        ),
    ]
